//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Customer()
        {
            this.Tbl_Order = new HashSet<Tbl_Order>();
        }
    
        public int Cu_ID { get; set; }
        public int Cu_Payment { get; set; }
        public string Cu_FirstName { get; set; }
        public string Cu_LastName { get; set; }
        public string Cu_Street { get; set; }
        public string Cu_ZipCode { get; set; }
        public string Cu_City { get; set; }
        public string Cu_PhoneNo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Order> Tbl_Order { get; set; }
        public virtual Tbl_Payment_Method Tbl_Payment_Method { get; set; }
    }
}
