//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Order()
        {
            this.Tbl_Order_Product = new HashSet<Tbl_Order_Product>();
        }
    
        public int Or_ID { get; set; }
        public int Or_Cu_ID { get; set; }
        public string Or_ToName { get; set; }
        public string Or_ToStreet { get; set; }
        public string Or_ToZipCode { get; set; }
        public string Or_ToCity { get; set; }
        public System.TimeSpan Or_OrderTime { get; set; }
    
        public virtual Tbl_Customer Tbl_Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Order_Product> Tbl_Order_Product { get; set; }
    }
}
